database-host= likelion-spring-3.cdmesi84kxr4.ap-northeast-2.rds.amazonaws.com
database-name = likelion_spring
database-username = admin
database-password = 00d08041!
googleOAuth-id="813243455001-nkebb134viniqnk88ju6s5i6kb1hqs82.apps.googleusercontent.com"
googleOAuth-password="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"